# -*- coding: utf-8 -*-
"""Проект ЦК.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hjy18OcFiZ9k86C0hG0AMLqhSohDwzau

1. Обработка исходного файла (приведение даты к формату datetime, удаление маркеров (достоинства, недостатки, комментарии))
"""

!pip install pymorphy3
import pandas as pd
import re
from datetime import datetime, timedelta
import nltk
from nltk.corpus import stopwords
import pymorphy3
from sklearn.feature_extraction.text import TfidfVectorizer

nltk.download('stopwords')

df = pd.read_excel('/content/all_reviews.xlsx')

months = {
    'января': '01', 'февраля': '02', 'марта': '03',
    'апреля': '04', 'мая': '05', 'июня': '06',
    'июля': '07', 'августа': '08', 'сентября': '09',
    'октября': '10', 'ноября': '11', 'декабря': '12'
}

def clean_date(date_str):
    if pd.isna(date_str):
        return None

    date_str = str(date_str)
    now = datetime.now()

    if 'Сегодня' in date_str:
        return now.date()

    if 'Вчера' in date_str:
        return (now - timedelta(days=1)).date()

    try:
        date_part = date_str.split(',')[0]
        day, month_text = date_part.split()
        month = months[month_text]
        year = now.year
        return datetime.strptime(f'{year}-{month}-{day}', '%Y-%m-%d').date()
    except Exception:
        return None

def remove_sections(text):
    if pd.isna(text):
        return ''

    text = str(text)
    text = re.sub(
        r'(Достоинства|Недостатки|Комментарий):?',
        ' ',
        text,
        flags=re.IGNORECASE
    )
    text = re.sub(r'\s+', ' ', text)

    return text.strip()

df['Дата'] = pd.to_datetime(df['Дата'].apply(clean_date))
df['Отзыв'] = df['Отзыв'].apply(remove_sections)

df.to_excel('/content/all_reviews_preprocessing.xlsx', index=False)

print('Файл предобработки сохранён: all_reviews_preprocessing.xlsx')

"""2. Предобработка (токенизация и лемматизация)"""

df_lemmas = pd.read_excel('/content/all_reviews_preprocessing.xlsx')

morph = pymorphy3.MorphAnalyzer()
stop_words = set(stopwords.words('russian'))

custom_stopwords = {
    'это', 'очень', 'просто', 'вообще', 'ещё', 'такой',
    'такая', 'такие', 'который', 'которые', 'нет', 'тушь', 'туши', 'туш', 'тушью', 'спасибо', 'ммм', 'тот', 'прям'
}

stop_words = stop_words.union(custom_stopwords)


def remove_emoji(text):
    emoji_pattern = re.compile(
        "["
        "\U0001F600-\U0001F64F"
        "\U0001F300-\U0001F5FF"
        "\U0001F680-\U0001F6FF"
        "\U0001F1E0-\U0001F1FF"
        "\U00002700-\U000027BF"
        "\U000024C2-\U0001F251"
        "]+",
        flags=re.UNICODE
    )
    return emoji_pattern.sub('', str(text))


def lemmatize_review(text):
    if pd.isna(text):
        return ''

    text = str(text).lower()
    text = remove_emoji(text)

    text = re.sub(r'[^а-яё\s]', ' ', text)

    tokens = text.split()

    tokens = [
        token for token in tokens
        if token not in stop_words and len(token) > 2
    ]

    lemmas = [
        morph.parse(token)[0].normal_form
        for token in tokens
    ]

    return ' '.join(lemmas)


df_lemmas['Отзыв_предобработанный'] = df_lemmas['Отзыв'].apply(lemmatize_review)

df_lemmas.to_excel('/content/all_reviews_normalized.xlsx', index=False)

print('Файл лемматизации сохранён: all_reviews_normalized.xlsx')

"""3. Ключевые слова



"""

df_keywords = pd.read_excel('/content/all_reviews_normalized.xlsx')

df_keywords['Отзыв_предобработанный'] = (
    df_keywords['Отзыв_предобработанный']
    .fillna('')
    .astype(str)
)

vectorizer = TfidfVectorizer(
    max_features=1000,
    ngram_range=(1, 1)
)

tfidf_matrix = vectorizer.fit_transform(df_keywords['Отзыв_предобработанный'])
feature_names = vectorizer.get_feature_names_out()

keywords_list = []

for row in tfidf_matrix:
    scores = row.toarray().flatten()
    top_indices = scores.argsort()[-5:][::-1]

    keywords = [
        feature_names[i]
        for i in top_indices
        if scores[i] > 0
    ]

    keywords_list.append(', '.join(keywords))

df_keywords['Ключевые_слова'] = keywords_list

df_keywords.to_excel('/content/all_reviews_keywords.xlsx', index=False)

print('Файл с ключевыми словами сохранён: all_reviews_keywords.xlsx')

"""4. Тематическое моделирование"""

!pip install bertopic
from bertopic import BERTopic
import pandas as pd
import numpy as np

# Загружаем модель для русского языка
model = BERTopic(language="russian")

# Загружаем данные
df = pd.read_excel("all_reviews_keywords.xlsx")

sample_df = df.head(942).copy()

# Очищаем данные:
sample_df['Отзыв_предобработанный'] = sample_df['Отзыв_предобработанный'].fillna('').astype(str)

sample_df = sample_df[sample_df['Отзыв_предобработанный'].str.strip() != '']

sample_texts = sample_df['Отзыв_предобработанный'].tolist()

# Запускаем модель
topics, probabilities = model.fit_transform(sample_texts)

# Выыодим 10 наиболее часто встречающихся тем
model.get_topic_freq().head(10)

#Посмотрим на самую частотную тему (Topic 0). Выводим первые 10 ключевых слов:
model.get_topic(0)[:10]

model.visualize_topics()  # визуализация тем

model.visualize_barchart()  # барчарт с распределением тем

model.visualize_hierarchy()  # иерархия тем

# Получаем информацию о темах
topic_info = model.get_topic_info()  # DataFrame с информацией о темах
print(topic_info)

"""5. Анализ тональности"""

!pip install transformers torch openpyxl tqdm

import pandas as pd
from transformers import pipeline
from tqdm import tqdm

tqdm.pandas()

# загрузка файла
df = pd.read_excel('all_reviews_keywords.xlsx')

# колонка с отзывами
df['Отзыв'] = df['Отзыв'].fillna('').astype(str)

# модель для русской тональности
sentiment_model = pipeline(
    "sentiment-analysis",
    model="cointegrated/rubert-tiny-sentiment-balanced",
    tokenizer="cointegrated/rubert-tiny-sentiment-balanced"
)

def get_sentiment(text):
    text = text.strip()

    if text == '':
        return pd.Series(['neutral', 0])

    # ограничение длины, чтобы модель не падала
    result = sentiment_model(text[:512])[0]

    label = result['label']
    score = result['score']

    # переводим тональность в числовой формат
    if label == 'positive':
        sentiment_score = score
    elif label == 'negative':
        sentiment_score = -score
    else:
        sentiment_score = 0

    return pd.Series([label, sentiment_score])

# применяем
df[['Тональность_класс', 'Тональность']] = df['Отзыв'].progress_apply(get_sentiment)

# сохраняем
df.to_excel('/content/all_reviews_sentiment.xlsx', index=False)

print('Файл сохранён: all_reviews_sentiment.xlsx')

import random

spisok = [random.randint(1, 50) for _ in range(len(df['Тональность']))]

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 5))
plt.scatter(df['Тональность'], spisok)
plt.title('Распределение тональности')
plt.xlabel('Средняя Тональность')
plt.show()

print(df['Тональность_класс'].value_counts())

examples_positive = df[df['Тональность_класс']  == 'positive'].head(5)
examples_positive

examples_negative = df[df['Тональность_класс']  == 'negative'].head(10)
examples_negative

examples_neutral = df[df['Тональность_класс']  == 'neutral'].head(10)
examples_neutral

"""Задание 5. Построить рейтинг ключевых слов по их средней тональности (усреднить по всем отзывам, где встречается данное слово). Ограничиться словами, которые встречаются не менее чем в 5 отзывах.

Визуализировать горизонтальную столбчатую диаграмму:
топ-10 самых позитивных слов (max средняя тональность).
топ-10 самых негативных слов (min средняя тональность).
(можно два отдельных графика или один с разными цветами).
"""

import pandas as pd
from collections import defaultdict
import matplotlib.pyplot as plt

df = pd.read_excel('/content/all_reviews_sentiment.xlsx')

df['Ключевые_слова'] = df['Ключевые_слова'].fillna('').astype(str)

word_sentiments = defaultdict(list)

# собираем тональности по словам
for _, row in df.iterrows():
    words = row['Ключевые_слова'].split(', ')
    sentiment = row['Тональность']

    for word in words:
        if word:
            word_sentiments[word].append(sentiment)

# считаем среднюю тональность и частоту
word_stats = []

for word, sentiments in word_sentiments.items():
    if len(sentiments) >= 5:  # фильтр по частоте
        avg_sent = sum(sentiments) / len(sentiments)
        word_stats.append((word, avg_sent, len(sentiments)))

# переводим в DataFrame
word_df = pd.DataFrame(word_stats, columns=['Слово', 'Средняя_тональность', 'Частота'])

# топ позитивных
top_positive = word_df.sort_values(by='Средняя_тональность', ascending=False).head(10)

# топ негативных
top_negative = word_df.sort_values(by='Средняя_тональность', ascending=True).head(10)

print(top_positive)
print(top_negative)

word_df

plt.figure(figsize=(10, 5))
plt.barh(top_positive['Слово'], top_positive['Средняя_тональность'])
plt.title('Топ-10 позитивных слов')
plt.xlabel('Средняя тональность')
plt.gca().invert_yaxis()
plt.show()


plt.figure(figsize=(10, 5))
plt.barh(top_negative['Слово'], top_negative['Средняя_тональность'])
plt.title('Топ-10 негативных слов')
plt.xlabel('Средняя тональность')
plt.gca().invert_yaxis()
plt.show()

"""Полина: задание 3. Сравнительный анализ проблем по площадкам.
- Для каждой платформы (Wildberries, Золотое Яблоко, Ozon) вычислите индекс проблемности по любым трем категориям, например, осыпание, склеивание, сложное удаление.
- Индекс = (количество отзывов, содержащих хотя бы одно слово из категории) / (общее число отзывов на площадке).
- Построить сгруппированную столбчатую диаграмму (площадки по оси X, категории проблем по оси Y – по три столбца на площадку).
"""

df_sentiment = pd.read_excel("/content/all_reviews_sentiment.xlsx")
df_neg = df[df["Тональность_класс"] == "negative"]
print(len(df_neg))

# ключевые слова
!pip install keybert

from keybert import KeyBERT
from collections import Counter

model = KeyBERT('DeepPavlov/rubert-base-cased')

# ключевые слова в каждом отзыве
all_keywords = []

for review in df_neg["Отзыв_предобработанный"].astype(str):  # переводим в строку, т.к. могут быть напр числа = ошибка
    keywords = model.extract_keywords(
    review,
    keyphrase_ngram_range=(1, 2), # и униграммы и биграммы, так чаще словосочетания с глаголами, что делает понятнее, негативный ли отзыв
    top_n=3 # извлекать 3 КС на 1 отзыв
)

    for keyword, score in keywords:
        all_keywords.append(keyword)

keyword_counts = Counter(all_keywords)

keyword_counts.most_common(40)

"""Категории повторяются (склеивание, прокрашивание, деньги), что визуально подсказывает самые частотные. + представлены разные леммы для одной категории, можно эти леммы включить в категории для анализа индексов"""

# словварь категорий проблем с их ключевыми словами

problem_categories = {
    "склеивание": [
        "склеивать", "склеить", "слипаться", "комок"
    ],

    "осыпание": [
        "осыпаться", "сыпаться"
    ],

    "нанесение": [
        "прокрашивать", "ложиться", "кисточка", "щёточка", "нанести", "неудобный"
    ]
}

# проверка отзыва на наличие ключевого слова из любой категории
def contains_keyword(review, keywords):
    words = review.split()

    for word in words:
        if word in keywords:
            return True

    return False

"""Индекс = кол-во отзывов с хотя бы одним словом категории / общее число отзывов на площадке с любой тональностью"""

results = []

platforms = df["Источник"].unique()

for category, keywords in problem_categories.items(): # метод items обращается и к ключу и к значению словаря

    for platform in platforms:
        # сколько отзывов на одной площадке
        df_platform = df[df["Источник"] == platform]
        total_reviews = len(df_platform)

        # сколько отзывов содержат любое слово из проблемных категорий
        count = 0

        for review in df_platform["Отзыв_предобработанный"].astype(str):
            if contains_keyword(review, keywords): # применяем пользовательскую функцию
                count += 1

        index = count / total_reviews

        # в пустой список подаем словари
        results.append({
            "Проблемная категория": category,
            "Площадка": platform,
            "Индекс": round(index, 2)
        })

result_df = pd.DataFrame(results)
result_df

# pivot перестраивает таблицу: значения старых столбцов превращает в строки и столбцы
new_result_df = result_df.pivot(
    index="Площадка", # площадки в строки
    columns="Проблемная категория", # категории в столбцы
    values="Индекс"  # индексы в ячейки
)

new_result_df

"""Столбчатая диаграмма (площадки по оси X, категории проблем по оси Y – по три столбца на площадку)."""

import matplotlib.pyplot as plt

new_result_df.plot(kind="bar")

plt.ylabel("Индекс")
plt.title("Индекс проблемности по площадкам")
plt.xticks(rotation=0)

plt.show()

"""- Нанесение - самая распространенная проблема, сбалансировано распределена
- Осыпания чаще на Озоне и меньше на Вб = мб разные партии
- ЗЯ: самые высокие индексы почти по всем категориям
"""